// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkbrqiknsraiskoybdry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rYnJxaWtuc3JhaXNrb3liZHJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MTEwODcsImV4cCI6MjA2MDM4NzA4N30.JUPus1q5WEBwXFC9cvqQnt6WEzM1ajqx71MAT9Tw0dk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);