
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables or fall back to hardcoded values if needed
// This ensures the app doesn't break during development and build
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://mkbrqiknsraiskoybdry.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rYnJxaWtuc3JhaXNrb3liZHJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MTEwODcsImV4cCI6MjA2MDM4NzA4N30.JUPus1q5WEBwXFC9cvqQnt6WEzM1ajqx71MAT9Tw0dk';

// Ensure we have the required values before creating the client
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Missing Supabase URL or Anon key. Check your environment variables.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
